name: Naukri Automation Bot

on:
  schedule:
    # Runs at 03:30 UTC, which is exactly 9:00 AM IST every day
    - cron: '30 3 * * *'
  workflow_dispatch: # Allows you to click "Run workflow" manually

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Automation Tests
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          CI: true
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml

      - name: Upload Screenshots on Failure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"